#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
polybar example &
xrandr --output Virtual-1 --mode 1920x1080 &
feh --bg-scale ~/.config/bgimages/BG.jpg &
setxkbmap -layout us,ru,ua -option 'grp:alt_shift_toggle' &
picom &
xsetroot -cursor_name left_ptr &

### WorckSpases

bspc monitor -d 1 2 3 4 5 6 7 8 9

### Borders

bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#25a487"

### Window Color When Selecting Its Position

bspc config presel_feedback_color "#25a487"

bspc config split_ratio          0.52

### Focus On Window On Mouse Hover

bspc config focus_follows_pointer true
bspc config pointer_modifier      super

### Monocle Mode

bspc config single_monocle       false
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle  true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
