#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
polybar main &
polybar second &
xrandr --output DP-0 --primary --auto --left-of DVI-D-0 --mode 1920x1080 --rate 143.98 &
xrandr --output DVI-D-0 --auto --right-of DP-0 --mode 1280x1024 --rate 76.00 &
feh --bg-scale ~/.config/bgimages/BG.jpg &
picom &
xsetroot -cursor_name left_ptr &
terminal="kitty"
flameshot &
redshift -O 4000 &

dunst -config $HOME/.config/bspwm/dunstrc &

firefox &
telegram-desktop &
discord &
pavucontrol &

### WorckSpases

bspc monitor DP-0 -d 1 2 3 4 5 6 7
bspc monitor DVI-D-0 -d 󰈹  

### Borders

bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#25a487"

### Window Color When Selecting Its Position

bspc config presel_feedback_color "#25a487"

bspc config split_ratio          0.52

### Focus On Window On Mouse Hover

bspc config focus_follows_pointer true
bspc config pointer_modifier      super

### Monocle Mode

bspc config single_monocle       false
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle  true

bspc rule -a firefox follow=off desktop="^8"
bspc rule -a TelegramDesktop follow=off desktop="^9"
bspc rule -a discord follow=off desktop="^9"
bspc rule -a pavucontrol follow=off desktop="^10"
